export const applicationActionTypes = {
  REQUEST_SEND_APPLICATION: 'REQUEST_SEND_APPLICATION',
  RECEIVE_SEND_APPLICATION: 'RECEIVE_SEND_APPLICATION',
  FAIL_SEND_APPLICATION: 'FAIL_SEND_APPLICATION'
};

export const contactActionTypes = {
  REQUEST_SEND_FEEDBACK: 'REQUEST_SEND_FEEDBACK',
  RECEIVE_SEND_FEEDBACK: 'RECEIVE_SEND_FEEDBACK',
  FAIL_SEND_FEEDBACK: 'FAIL_SEND_FEEDBACK'
};
