const actionTypes = {
  REQUEST_SEND_APPLICATION: 'REQUEST_SEND_APPLICATION',
  RECEIVE_SEND_APPLICATION: 'RECEIVE_SEND_APPLICATION',
  FAIL_SEND_APPLICATION: 'FAIL_SEND_APPLICATION',

  REQUEST_SEND_FEEDBACK: 'REQUEST_SEND_FEEDBACK',
  RECEIVE_SEND_FEEDBACK: 'RECEIVE_SEND_FEEDBACK',
  FAIL_SEND_FEEDBACK: 'FAIL_SEND_FEEDBACK',

  REQUEST_GET_CURRICULUM: 'REQUEST_GET_CURRICULUM',
  RECEIVE_GET_CURRICULUM: 'RECEIVE_GET_CURRICULUM',
  FAIL_GET_CURRICULUM: 'FAIL_GET_CURRICULUM',

  REQUEST_GET_PROGRESSES: 'REQUEST_GET_PROGRESSES',
  RECEIVE_GET_PROGRESSES: 'RECEIVE_GET_PROGRESSES',
  FAIL_GET_PROGRESSES: 'FAIL_GET_PROGRESSES',

  RECEIVE_ERROR: 'RECEIVE_ERROR',
  MARK_ERRORS_AS_DISPLAYED: 'MARK_ERRORS_AS_DISPLAYED'
}

export default actionTypes
