import dotenv from 'dotenv';
dotenv.config();

export default {
  'CURRICULUM_ENABLED': process.env.CURRICULUM_ENABLED,
  'FACILITATOR_GUIDE_ENABLED': process.env.FACILITATOR_GUIDE_ENABLED,
  'FACILITATOR_SIGN_IN': process.env.FACILITATOR_SIGN_IN,
  'LESSON_NOTES_ENABLED': process.env.LESSON_NOTES_ENABLED,
  'ABOUT_US_ENABLED': process.env.ABOUT_US_ENABLED,
  'CONTACT_US_ENABLED': process.env.CONTACT_US_ENABLED,
  'VOLUNTEER_PAGE_ENABLED': process.env.VOLUNTEER_PAGE_ENABLED,
  'MISSION_PAGE_ENABLED': process.env.MISSION_PAGE_ENABLED,
  'BLOG_PAGE_ENABLED': process.env.BLOG_PAGE_ENABLED
};
